### ISSUE TITLE
Is non-english Gherkin syntax supported ?

### ISSUE THREAD

**Issue by StyMaar** [bbqsrc/cucumber-rust#100]
Cucumber supports a [wide list of languages](https://cucumber.io/docs/gherkin/languages/) for the gherkin syntax, does Cucumber-rust support any of those ?

**Comment by bbqsrc** [comment]
Since the last patch release, all of them. Try it out. 😄

**Comment by StyMaar** [comment]
@bbqsrc so cool ! I couldn't make it work, but I was using v0.7 (after reading [this tutorial](https://www.florianreinhard.de/2020-08-16/cucumber-in-rust-beginners-tutorial/) which is linked in the README).

**Comment by StyMaar** [comment]
```
Error parsing '/home/stymaar/dev/encrsypter/tests/features/yolo.feature':
Unknown keyword: 'Fonctionnalit'.
ParseError { location: LineCol { line: 1, column: 14, offset: 13 }, expected: ExpectedSet { expected: {"unknown keyword"} } }
```
Hm, at least the error message is better than in 0.7 but it still doesn't work.

**Comment by bbqsrc** [comment]
Share your feature file?

**Comment by StyMaar** [comment]
```Toml
[[package]]
name = "cucumber_rust"
version = "0.8.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7c89fcfe82630886699e0298e3c02b997555e8706bb66ecf6e121933099aff7f"
```
from cargo.lock

**Comment by StyMaar** [comment]
```feature
Fonctionnalité: Encrypt messages and write them to a file.

Scénario: Encrypt a simple Hello World - message.
  Étant donné I have an encryptor initialized with input "Hello World!"
     Alors I should see "Hello World!" in the encryptor's input field
     Quand I encrypt the encryptor's input
     Alors testfile.txt exists
      Et testfile.txt is not empty
     Quand I decrypt testfile.txt
     Alors the decrypted result should be "Hello World!"
```

**Comment by StyMaar** [comment]
(I literally took the one in the aforementioned example, and put the French version of the keywords)

**Comment by bbqsrc** [comment]
It is required by Cucumber that you specify the language, so add `# language: fr` at the top and it should work.

**Comment by StyMaar** [comment]
Oh, it works indeed! Thanks a lot

**Comment by bbqsrc** [comment]
This will get annoying if your whole project is going to use that language though. I think I'll make a feature request item to allow specifying which language in the `Cargo.toml` as well, so it will default to that language.

Glad I helped. :smile:

**Comment by StyMaar** [comment]
I think I would survive without it, but it's still a good idea!
