### ISSUE TITLE
Capture stdout on test success

### ISSUE THREAD

**Issue by theredfish** [bbqsrc/cucumber-rust#107]
Hello,

I'm trying to use the following configuration : `enable_capture(true)`.
It works on failures, but not on successes. Is there a way to print information during a valid test case? I would like to attach extra information to my steps. I don't know if `enable_capture` is intended to work in this particular case.

- [See this repo for a reproductible case](https://github.com/theredfish/cucumber-rust-enable-capture/blob/6ba773ab14afb33747bbac7dc60f0f3054a8502d/tests/cucumber.rs#L53) : "I should print during a success case" isn't displayed on the standard output.

Once [assert!(false)](https://github.com/theredfish/cucumber-rust-enable-capture/blob/6ba773ab14afb33747bbac7dc60f0f3054a8502d/tests/cucumber.rs#L63) is removed (I tested if the log is displayed in case of failures), the output is the following : 
```bash
[Cucumber v0.8.4]
Feature: Example feature                                                                                                                                                         tests/features/example.feature:1:1 

 Scenario: An example scenario                                                                                                                                                   tests/features/example.feature:3:3 
  ✔ Given I am trying out Cucumber                                                                                                                                               tests/features/example.feature:4:5 
  ✔ When I consider what I am doing                                                                                                                                              tests/features/example.feature:5:5 
  ✔ Then I am interested in ATDD                                                                                                                                                 tests/features/example.feature:6:5 
  ✔ And we can implement rules with regex                                                                                                                                        tests/features/example.feature:7:5 

[Summary]
1 features
1 scenarios (1 passed)
8 steps (4 passed)
```

Thank you!

**Comment by bbqsrc** [comment]
Add `.debug(true)` instead.

**Comment by theredfish** [comment]
Thank you it was what I was looking for :)
