### ISSUE TITLE
test reuse / parameterized tests

### ISSUE THREAD

**Issue by vandenoever** [bbqsrc/cucumber-rust#11]
Is it possible to run the same tests on different `Trait` implementations? The implementations of the Trait should behave the same and would have the same feature file text.
The `Trait` implementations would presumably be instantiated in separate setup functions. What would be a concise way of writing the feature files and tests in such a scenario?

**Comment by jakob-ledermann** [comment]
I tried to get your described use case running.
As a sample I used the following trait:
`
pub trait Sorter {
    fn sort(&self, source: &[i64]) -> Box<[i64]>;
}`

I wanted to reuse the following definitions:
* the feature-file
* the step definitions
* the world definition

So I needed to store my tested implementation inside the struct MyWorld. As I do not know which implementation should be testet, while implementing the trait Default, I dropped the requirement for implementing Default and replaced it with a factory function.
This function must be supplied to the macro cucumber!

First I tried to achive it without changing anything in the crate but unfortunately neither a before_fn nor the
`fn setup() {}` have access to the world, i settled for this aproach as it is the least invasive at the moment.

I am at the moment not entirely happy with my current implementation so I don't feel it is ready for a pull request yet. But maybe you could check whether:
1. you are able to achive your goal with my patched version
n. my sample and goals for the sample are what you wanted to do in your request.
