### ISSUE TITLE
Colors when output is not a TTY

### ISSUE THREAD

**Issue by rudolphfroger** [bbqsrc/cucumber-rust#119]
Currently Cucumber is using color codes even when the output isn't a TTY. For example in Jenkins one can see output like this:

    [0m[1m[34m[Summary]
    [0m[0m[1m[37m1 features
    [0m[0m[1m[37m1 scenarios ([0m[0m[1m[32m1 passed[0m[0m[1m[37m)
    [0m[0m[1m[37m6 steps ([0m[0m[1m[32m3 passed[0m[0m[1m[37m)
    [0m

I haven't tried but I can see one place which enforces the use of colors, in `macros.rs` there's usage of `ColorChoice::Always`. The `termcolor` crate gives an example on how to detect the presence of a terminal and set `ColorChoice` accordingly.

**Comment by tyranron** [comment]
Resolved in #128
