### ISSUE TITLE
v. 0.9.0: Setting the default language in the Cucumber builder is not applied during test execution

### ISSUE THREAD

**Issue by florianrein** [bbqsrc/cucumber-rust#126]
**Prereqs**
- 2 Feature Files doing exactly the same, but one is using default Gherkin keywords in English, and one uses German keywords
- the latter has the magic comment: `# language: de`
- .language("de") is set in the creation of the runner

**Steps to reproduce**
1. cargo clean
2. cargo test

**Actual Result**
Both feature files are executed.

**Expected Result**
An error message should be thrown stating that the keywords in the English feature file could not be evaluated.

---

Hi Brendan, Hi Fellows, 
while doing a writeup about the changes since the 0.8 release, I conducted the above experiment.
In the process I noticed that the .language("de") call seems not to be applied. 
Am I missing something or do we have an actual bug?
My full code is located [here](https://bitbucket.org/florianreinh/encrsypter/src/0.9.0_language_feature/tests/).
The relevant files are ./features/* and cucumber.rs .

**Comment by bbqsrc** [comment]
Probably a bug. Hope to look at it soon, a bit of a strange regression that one.

**Comment by tyranron** [comment]
Fixed in #128
