### ISSUE TITLE
Example in README doesn't compile

### ISSUE THREAD

**Issue by projektir** [bbqsrc/cucumber-rust#26]
Trying to add `cucumber-rust` to a new project. Rust version:
```
stable-x86_64-unknown-linux-gnu (default)
rustc 1.35.0 (3c235d560 2019-05-20)
```

Added the changes to `Cargo.toml`, the `tests` directory, the `features` directory, at project root, as in the example. `cucumber.rs` was copied verbatim from the README, but to make sure: [cucumber.rs](https://gist.github.com/projektir/6263f95d3d288793e399df38dba04b1d)

When running `cargo test`, observing the following error:

```
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/projektir/.cargo/registry/src/github.com-1ecc6299db9ec823/cucumber_rust-0.5.1/src`/lib.rs:9:34
  |
9 | #![cfg_attr(feature = "nightly", feature(set_stdio))]
  |                                  ^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

I've changed my `Cargo.toml` to include the following:

```
cucumber_rust = { version = "^0.5.1", default-features = false }
```

And started getting these errors instead (I also get them if I just change to nightly):
```
error[E0412]: cannot find type `MyWorld` in the crate root
  --> tests/cucumber.rs:21:14
   |
21 |     steps!(::MyWorld => {
   |              ^^^^^^^ not found in the crate root

error[E0412]: cannot find type `MyWorld` in the crate root
  --> tests/cucumber.rs:78:14
   |
78 |     world: ::MyWorld, // The world needs to be the same for steps and the main cucumber call
   |              ^^^^^^^ not found in the crate root
help: possible candidate is found in another module, you can import it into scope
   |
4  | use crate::MyWorld;
   |

error[E0609]: no field `foo` on type `&mut _`
  --> tests/cucumber.rs:23:19
   |
23 |             world.foo = "Some string".to_string();
   |                   ^^^

error[E0609]: no field `foo` on type `&mut _`
  --> tests/cucumber.rs:29:52
   |
29 |             let new_string = format!("{}.", &world.foo);
   |                                                    ^^^

error[E0609]: no field `foo` on type `&mut _`
  --> tests/cucumber.rs:35:30
   |
35 |             assert_eq!(world.foo, "Some string.");
   |                              ^^^

error: aborting due to 5 previous errors
```

**Comment by adam-rhebo** [comment]
@projektir I think you are building your example using Rust edition 2018 but the examples are meant for edition 2015. Try using `crate::MyWorld` as the compiler suggests.

@bbqsrc Maybe we want to bump the examples to Rust edition 2018 as this is the default when running `cargo init` by now?

**Comment by projektir** [comment]
Oh, that looks to be it! I changed the `::MyWorld` instances to `crate::MyWorld` and it compiles now. I thought about editions before but I'm not very familiar with the differences between them, and `cucumber-rust` itself is on 2018 so I thought I was safe. :satisfied:

Note: the issue with nightly still persists. Perhaps the tip about disabling default features should be added back in?

**Comment by adam-rhebo** [comment]
> Note: the issue with nightly still persists. Perhaps the tip about disabling default features should be added back in?

The version on `master` here does not require the unstable features anymore. So I guess we should create a release so that the README matches the code that is shipped via crates.io...

**Comment by bbqsrc** [comment]
I'll put out a new release tonight. 👍

**Comment by bbqsrc** [comment]
New version is up now. :smile:
