### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by bbqsrc** [bbqsrc/cucumber-rust#30]
- [x] Add builders to supplement the `cucumber!` and `steps!` macros
- [x] Support asychronous tests
- [ ] Review handling and ergonomics of data tables

**Comment by humb1t** [comment]
Hi @bbqsrc, can you tell me about support for asynchronous tests?
I'm trying to work with tokio runtime from `steps`, but it seemed that it's unavailable from them:
```
  called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }
```

**Comment by bbqsrc** [comment]
Async only exists in my [WIP branch](https://github.com/bbqsrc/cucumber-rust/pull/32). It's not up-to-date since futures 0.3 was released, and predates tokio 0.2 as well.

Right now I'm kind of just waiting for the dust to settle a bit more around how to handle executors and all that garbage, so unless someone else wants to work on that WIP branch themselves and experiment, it's going to be a few more months yet before async support.

**Comment by humb1t** [comment]
@bbqsrc - thanks, I will check and try to contribute.

**Comment by bbqsrc** [comment]
Feel free to ask any questions about it on that PR. Happy to help
