### ISSUE TITLE
Feature: `cucumber! { teardown: fn(...) }` to mirror `setup: fn(...)`

### ISSUE THREAD

**Issue by brycefisher** [bbqsrc/cucumber-rust#38]
I'd like to use this library to start docker containers using the `setup` fn and then destroy those same containers after the cucumber test run finishes. I couldn't see a `teardown` in the `cucumber` macro on docs.rs. It would be super handy to use a `teardown` to cleanup resources created in `setup.`

**Comment by bbqsrc** [comment]
Won't be added until after the current `cucumber!` macro is converted to a procedural macro, as the current machinations for handling all those parameter fields is a mess and needs to be stopped. 😄

**Comment by brycefisher** [comment]
Gotcha!! Thanks for providing some insight. Seems totally reasonable to me

**Comment by bbqsrc** [comment]
Current status: I don't think we're going to need this. On the develop branch, there's an async-first implementation that has gotten rid of any "magic". With no macro, and just an ordinary builder, you can put any setup and teardown around the runner that you call yourself anyway.
