### ISSUE TITLE
Bug: Setup executes 2x

### ISSUE THREAD

**Issue by brycefisher** [bbqsrc/cucumber-rust#39]
For me, the `setup()` fn always runs twice in a row at the beginning of my test run. I've made as minimal a reproduction case as possible in this repo:
https://github.com/brycefisher/cucumber-rust-issue-39

![](https://github.com/brycefisher/cucumber-rust-issue-39/blob/master/repro.svg)

Steps to reproduce:
 1. git clone https://github.com/brycefisher/cucumber-rust-issue-39
 2. Using rust 1.40, execute `cargo test` in the root directory

Expected behavior: Cucumber-rust should output "Setup run 1 times"

Actual behavior: Cucumber-rust prints "Setup ran 1 times\nSetup ran 2 times"

**Comment by bbqsrc** [comment]
Published as v0.6.4. Thanks!

**Comment by brycefisher** [comment]
Can confirm this resolved the issue for me! Thank you.
