### ISSUE TITLE
Feature: output elapsed time for tests

### ISSUE THREAD

**Issue by matthewkmayer** [bbqsrc/cucumber-rust#45]
Thanks for the library, I'm exploring using it instead of other Cucumber implementations.

With the Ruby implementation of Cucumber, the elapsed test run time is printed at the end of the run, like so:

```bash
8 scenarios (8 passed)
28 steps (28 passed)
1m36.877s
```

It'd be 💯 to see elapsed test run time printed in this library as well. 😄

**Comment by bbqsrc** [comment]
I don't have time to implement this feature at the moment, but I'd be happy to accept a pull request adding it.

Slap a time in the `DefaultOutput` struct, get the current time in the `visit_start` function of the `impl OutputVisitor for DefaultOutput` and then print the final time in `visit_finish`. :smile:

**Comment by bbqsrc** [comment]
@matthewkmayer this now exists on develop branch. :+1:
