### ISSUE TITLE
Comment - Parsing feature failed

### ISSUE THREAD

**Issue by ami44** [bbqsrc/cucumber-rust#6]
Hello, 

I have this error when last line in feature is commented (without \n after ``# When something goes wrong``)

```feature
Feature: Basic functionality

  Scenario: foo
    Given a thing
    When nothing

  # Scenario: bar
    # Given a thing
    # When something goes wrong
```

then ``cargo +nightly test`` display

```
———— ! Parsing feature failed: —————————————————————— features/test.feature:9:5
   --> 9:5
    |
  9 |     # When something goes wrong
    |     ^---
    |
    = expected tag or examples
————————————————————————————————————————————————————————————————————————————————
```

No error if \n after ``# When something goes wrong``

Ami44

**Comment by bbqsrc** [comment]
Fixed in the `gherkin-rust` dependency. Thanks!

It should update automatically, otherwise `cargo update` should pick it up.
