### ISSUE TITLE
Print running step when executing, not when done

### ISSUE THREAD

**Issue by nbigaouette** [bbqsrc/cucumber-rust#65]
I have some steps that are long to execute, for example I poll an external system for updates which can take minutes.

With 0.7 the step's name will be printed at the end of execution, either in green if passed or red if failed.

It would be great if the step's name were printed (in neither green nor red) with an indication that the step is running. When done, the final red/green line could be shown.

**Comment by bbqsrc** [comment]
Should be rather straightforward.

Extend the `StepEvent` enum to have a `Starting` event, then `yield` it in all the right places (basically search for `ScenarioEvent::Step` and it should be fairly obvious).

Then you update `output/default.rs` to handle that event. On Unix, you can get away with doing a print then a flush, then when you want to write again doing a `\r` to return to the beginning of the line. On Windows, I don't know, but we need compat with both. :smile:

**Comment by nbigaouette** [comment]
Would you find [indicatif](https://docs.rs/indicatif/) interesting? It might provide this kind of dynamism without having to handle special characters oneself...

**Comment by Baev1** [comment]
Hi! I would like to give this a try if that's alright?
I think you can just write the name of the step to stdout when the step started, set a bool on BasicOutput to true and then when next calling BasicOutput::handle_step delete the last line printed using ANSI escape codes if that bool has been set?

**Comment by bbqsrc** [comment]
Hi @Baev1 😄 

That sounds like one way to do it, yes. Worth a shot at least!

**Comment by bbqsrc** [comment]
You will still probably need to at least extend the `StepEvent` enum to have a Starting event, as right now there's no way to see that a step has started in the event model.

I also still don't know how to handle printing a clearable line on Windows, haha.

**Comment by bbqsrc** [comment]
@nbigaouette I did actually try indicatif on a branch when I was trying parallel scenario runners. It uh, didn't go great. It's not very async friendly yet (lots of things aren't unfortunately).
