### ISSUE TITLE
Filtering scenarios removed in 0.7?

### ISSUE THREAD

**Issue by liamcurry** [bbqsrc/cucumber-rust#67]
In 0.6 there were CLI options to filter scenarios based on globs and/or tags, is that no longer available in 0.7?

**Comment by bbqsrc** [comment]
It should still be there. Can you describe the problem that you're facing?

**Comment by bbqsrc** [comment]
Oh, are globs being ignored? I might have just forgotten to re-add that during the refactor!

**Comment by liamcurry** [comment]
I'm not seeing anything obvious in the docs https://docs.rs/cucumber_rust/0.7.2/cucumber_rust/struct.Cucumber.html

To be clear I'm talking about the options here https://docs.rs/cucumber_rust/0.6.9/cucumber_rust/cli/struct.CliOptions.html
