### ISSUE TITLE
Emoji in default output causes width calculation to be incorrect

### ISSUE THREAD

**Issue by nbigaouette** [bbqsrc/cucumber-rust#71]
One of my step has two emojis in its name (🦀). This seems to break the terminal width calculation used to send the file/number on the right side. See how the column number (9) gets sent to a new line in the screenshot:

<img width="1107" alt="Screen Shot 2020-09-23 at 11 18 03 AM" src="https://user-images.githubusercontent.com/112988/94033180-b27de580-fd8e-11ea-861c-b2e24072d8c3.png">

I suspect it could be caused by bad calculation of the emoji's UTF-8 width. Interestingly, the problem does not happen if I have _one_ emoji in the name. Weird... 🤔

EDIT: This is on macOS Catalina 10.15.6 using iTerm2 3.3.12 and tmux.

**Comment by bbqsrc** [comment]
Terminals all render emoji widths differently, so this isn't something I intend to mitigate personally. It's a known issue with how monospaced fonts, terminal renderers and Unicode interact.

Happy to leave this open if someone wants to try to tackle this, but forewarning that it's an endless pit of despair and nothing good comes of it. tl;dr computers mean we can't have nice things. haha

**Comment by nbigaouette** [comment]
😂 
👍

**Comment by bbqsrc** [comment]
Hum, this may not be the time sink I expect. There's a crate: https://github.com/unicode-rs/unicode-width

We could just use this. It won't fix everything I suspect, but it'll work in more cases than we currently handle. Slap this everywhere I currently did a width calculation and we'll have a better life.

**Comment by bbqsrc** [comment]
_Definitely_ read https://github.com/unicode-rs/unicode-width/issues/4 if you're going to tackle this, though. Maybe I removed time sink too soon, I'll put it back, ahaha

**Comment by tyranron** [comment]
Fixed in #128
