### ISSUE TITLE
Aruba support

### ISSUE THREAD

**Issue by bbros-dev** [bbqsrc/cucumber-rust#74]
Thank you for the effort put into making cucumber-rust.  It is appreciated.

Has any thought been given to implementing Aruba's steps? 
https://github.com/cucumber/aruba

Either separately or within cucumber-rust as some CLI domain specific sane defaults?

If not cucmber-rust: Does anyone know of such a library/framework where this type of effort might sit? 
I know of speculate.rs, but it seems to be dead.

**Comment by bbqsrc** [comment]
Can you show me an example of this in use? I'm not quite grasping what this does from that link alone. :smile:

**Comment by bbros-dev** [comment]
> Can you show me an example of this in use? 

Sure, many:
https://github.com/cucumber/aruba/tree/master/features

> I'm not quite grasping what this does from that link alone.

Generally web apps are snowlfakes in terms of the UI - no two alike - so you want to write custom steps (though there are libraries of web oriented steps)

However CLI apps have a UI that is much more constrained (stdin, stdout, stderr).
Aruba is a set of CLI domain specific steps - specialized to CLI apps.  Generally no one wants to implement that common functionality from scratch.

Generally Aruba gets included in a project and the step definitions are avaiable there.
Hope that is clearer?

**Comment by bbqsrc** [comment]
It seems that it is effectively a set of predefined steps then, with some special tags that behave as directives?

Is there anything fundamental to this that couldn't be implemented as a separate crate that just predefined steps to be used?

**Comment by bbros-dev** [comment]
> Is there anything fundamental to this that couldn't be implemented as a separate crate that just predefined steps to be used?

No, that is my recollection of the implementation - but it has been a few years.
The issue might be how it seamlessly integrates with cucumber-rust, but I'm a total rust noob. Seriously, don't listen to me - I can't even get cucumber running: issue #76

**Comment by bbros-dev** [comment]
I should point out one natural use case is people porting some CLI app from ruby, python, etc to rust.
If they have feature files using Aruba steps then things will Just-Work(TM)

**Comment by bbqsrc** [comment]
I think this would be better tackled in another crate. Thanks for your interest.
