### ISSUE TITLE
The CI badge on the README points to the wrong project

### ISSUE THREAD

**Issue by saveriomiroddi** [bbqsrc/cucumber-rust#79]
The CI badge on the README points to the wrong project - it points to https://github.com/bbqsrc/box/actions.

**Comment by bbqsrc** [comment]
Shhhh, if I change it to point to this repo people will know my builds fail. 😉 

I have no idea when I broke this but I'll fix it now.

**Comment by bbqsrc** [comment]
Fixed. It was just the link fortunately, the image was pointing to the correct repo, haha. Thanks!

**Comment by saveriomiroddi** [comment]
Wow, that was fast. I was opening a PR, and couldn't reproduce the problem. Took me a while to figure out you'be been Extremely Efficient™ :laughing:

Thanks for your work!
