### ISSUE TITLE
Feature path with sub-directories

### ISSUE THREAD

**Issue by bhase** [bbqsrc/cucumber-rust#8]
Hello,
currently a feature path containing more than .feature files is not handled correctly, both sub-directories and files with other content than gherkin provoke a failure in the test run.

I noticed this when trying to adept to cucumber conventions, i.e. having a folder 'step_definitions' below 'features' containing rust files with the steps. IMHO it would be good to travel sub-directories while only accepting files ending with .feature.

Is this the place where the change needs to go in?
https://github.com/bbqsrc/cucumber-rust/blob/42f7e5eeaaf1df29ffca083fb9abaa49aa31d3c1/src/lib.rs#L340-L353

**Comment by bbqsrc** [comment]
Yes, that seems like the right spot. You may want to use the [glob](https://github.com/rust-lang-nursery/glob) crate to simplify your solution if you want to take a crack at it. :smile:

**Comment by bhase** [comment]
Great, I will give it a try. Thank you for the hint to glob!

**Comment by bbqsrc** [comment]
Implemented using `globwalk` because `glob` is basically deprecated.
