### ISSUE TITLE
Reducing boilerplate with proc macros

### ISSUE THREAD

**Issue by tyranron** [bbqsrc/cucumber-rust#81]
In our codebase we've built some proc macro machinery, which allows us to reduce boilerplate using this library. An example could've looked something like this:
```rust
use std::convert::Infallible;

use async_trait::async_trait;
use cucumber::gherkin::Step;
use cucumber_codegen::given;

#[derive(cucumber_codegen::World)]
pub struct World {
    pub foo: i32,
}

#[async_trait(?Send)]
impl cucumber::World for World {
    type Error = Infallible;

    async fn new() -> Result<Self, Self::Error> {
        Ok(Self { foo: 0 })
    }
}

#[given(regex = r"(\S+) is (\d+)")]
async fn test_regex_async(
    w: &mut World,
    step: String,
    #[given(step)] s: &Step,
    num: usize,
) {
    tokio::time::delay_for(std::time::Duration::new(1, 0)).await;

    assert_eq!(step, "foo");
    assert_eq!(num, 0);
    assert_eq!(s.value, "foo is 0");

    w.foo += 1;
}

#[tokio::main]
async fn main() {
    use cucumber_codegen::WorldInit as _;

    let runner = World::init(&["./features"]);
    runner.run().await;
}
```
Under-the-hood it uses code generation via proc macros, some additional glue type definitions, and `inventory` for automatic step assertions registration.

We want to make public that machinery.

Are you interested with adding all of that to this crate? Or should we go with a diffent one?

**Comment by bbqsrc** [comment]
I'd be pretty happy to integrate that, sure. 😄

**Comment by bbqsrc** [comment]
Hey @tyranron, need any assistance with the integration work?

**Comment by tyranron** [comment]
@bbqsrc nope, thanks. I'm just quite a bit limited in time dedicated to this. Will try to land it this/next week.
