### ISSUE TITLE
README misleads newer Rust devs and doesn't result in runnable tests

### ISSUE THREAD

**Issue by rawkode** [bbqsrc/cucumber-rust#83]
This seems undocumented here, but I could only get the example from the README.md to work when adding:

```rust
futures = { version = "0.3", features = ["compat"] }
```

**Comment by bbqsrc** [comment]
What is it that the `compat` feature gives? Even Cucumber itself doesn't use that feature so I find this issue strange.

The `cucumber_builder.rs` test is basically analogous to the README, does it break running `cargo test` on the repo directly?

**Comment by rawkode** [comment]
OK. It looks like I need to explicitly add this to `Cargo.toml`


```rust
[dev-dependencies]
futures = { version = "0.3" }
cucumber = { package = "cucumber_rust", version = "^0.7.0" }
async-trait = "0.1.41"
```

The `compat` was a red herring, as I copied that from the futures docs.

Even though cucumber has these as dependencies, I still need to manually add them.

This could be expected behaviour, I'm pretty new to Rust.

**Comment by bbqsrc** [comment]
No problem. I think the proper idea here is I need to remove the example from the README and link directly to the files in the tests directories; maintaining these in tandem and having people understand how to use them has been pain.

That said, someone is soon to contribute a proc-macro variant that should make using Cucumber in Rust a bit more of a pleasure, masking a significant amount of complexity.

I'll mark this one as a documentation issue and see to it that we do something to make the beginner's experience a bit more painless, as I can say for certain I had not even considered people coming to Cucumber as an _entrypoint to Rust_. :smile: Such is time I suppose -- this space has grown so quickly I can't keep up haha.

Perhaps a book I am guaranteed to never finish is a good starting point... 😉

**Comment by alvskar** [comment]
The Readme should be a bit more newbie friendly now.
