### ISSUE TITLE
Test failure cannot be detected

### ISSUE THREAD

**Issue by nbigaouette** [bbqsrc/cucumber-rust#84]
I want to run my cucumber tests and fail the whole execution if a step fails.

Right now, there does not seem to be the case; Looking at `Cucumber::run()` the steps are simply executed in a `while` loop:
https://github.com/bbqsrc/cucumber-rust/blob/7140ba0d7314cd8863d7c290e8e31c2a/src/cucumber.rs#L145-L158

In my code base I isolate my call to `Cucumber::run()` in a separate crate (where all my steps/tests are defined) and re-use them in either a CLI or a webapp. This allows me to run some integration tests either locally or side-by-side with the system being tested (required due to auth issues).

Right now, I realize that I have no way of detecting if a test failed or not without looking at stdout/err, which makes running in service not as useful as it should be.

Searching the code base I found commits relating to exit code, for example 6bee78856c5ca20e6cf1601e2eb71072fdb5d8e7. This one uses `std::process:exit(1)` which is not what I need, but it seems the intent was to propagate the error to the caller.

I think the simplest would be to let `Cucumber::run()` return a `Result<>` instead of nothing? That way one can unwrap/assert/check/... the actual result of the test.

**Comment by bbqsrc** [comment]
I don't have time to look into this but I'd be happy to receive an experimental pull request that solves your problem then discuss the appropriate API changes to make it generally useful. 🙂

**Comment by bbqsrc** [comment]
So my understanding of your requirements based on your example PR is to be able to programmatically determine the outcome of a test run. Entirely reasonable.

Would it not make more sense for us to return an object similar to https://doc.rust-lang.org/std/process/struct.Output.html?

A standard "Output" object could contain total tests run, total errors, etc, with a basic `success` boolean for if anything failed, and then the complex data if you want to dig.

We could add a `run_and_exit` function that returns nothing, but exits the process with `1` is the `success` value is `false`. Does this sound good?

**Comment by bbqsrc** [comment]
To clarify, I proposed changing the return type of `run` to return this "Output" object, and add an additional convenience wrapper for the test runner that automatically returns an exit code on failure, which would be called `run_and_exit`.

**Comment by nbigaouette** [comment]
That's perfect! :D

**Comment by bbqsrc** [comment]
This is in `main` now. Will be in v0.8. :)
