### ISSUE TITLE
README is confusing - it possibly has errors

### ISSUE THREAD

**Issue by saveriomiroddi** [bbqsrc/cucumber-rust#90]
Hello!

I went through the README in order to test the crate, however, I find it very confusing, because it doesn't run with a simple copy/paste. I'm a beginner though, so possibly, all of this is evident to an experienced programmer, however, I think it'd be good to have a README that shows a procedure that can be copy/pasted, and run directly.

I'll post here the procedure I've run, with my comments.

First, create the project (no need to add this):

```sh
cargo new --bin try_cucumber
cd try_cucumber
```

Now, I find the Cargo.toml a bit beginner unfriendly, because it uses two crates that are not specified. My suggestion is to add them to the README:

```sh
cat >> Cargo.toml <<TOML
async-trait = "0.1.42" # <== this...
futures = "0.3.8"  # <== ... and this

[[test]]
name = "cucumber"
harness = false # Allows Cucumber to print output instead of libtest

[dev-dependencies]
cucumber = { package = "cucumber_rust", version = "^0.7.0" } 
TOML
```

The procedure of the readme follows, so no need for changes also here:

```sh
mkdir features

cat > features/examples.feature <<CUCUMBER
Feature: Example feature

  Scenario: An example scenario
    Given I am trying out Cucumber
    When I consider what I am doing
    Then I am interested in ATDD
    And we can implement rules with regex
CUCUMBER

mkdir tests

cat > tests/cucumber.rs <<RUST
use async_trait::async_trait;
use std::{convert::Infallible, cell::RefCell};

// ETC ETC
```

Now, here there's a problem: the crate requires Rust nightly (as far as I understand), so the command `cargo test ...` specified won't work, unless the dev is running nightly by default. I think it should be therefore changed to:

```rust
cargo test +nightly --test cucumber
```

or suggested to add `rust-toolchain`:

```rust
echo nightly > rust-toolchain
```

Now, here there is a problem that I couldn't solve. Running the example now yields:

```rust
error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<impl futures::Future>` in the current scope
  --> tests/cucumber.rs:40:17
   |
40 | /                 t!(|mut world, _step| {
41 | |                     world.foo = "elho".into();
42 | |                     world.test_async_fn().await;
43 | |                     world
44 | |                 }),
   | |__________________^ method not found in `AssertUnwindSafe<impl futures::Future>`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use futures::FutureExt;`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `cli` found for struct `Cucumber<MyWorld>` in the current scope
  --> tests/cucumber.rs:83:10
   |
83 |         .cli();
   |          ^^^ method not found in `Cucumber<MyWorld>`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `try_cucumber`

To learn more, run the command again with --verbose.
```

I'm not sure what this is.

There is also a problem with the macro Cargo configuration.

If I configure Cargo as explained:

```sh
[package]
authors = ["xxx <xxx@xxx.invalid>"]
edition = "2018"
name = "try_cucumber"
version = "0.1.0"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.8"

[[test]]
harness = false # Allows Cucumber to print output instead of libtest
name = "cucumber" 

[dev-dependencies]
cucumber_rust = {version = "^0.7.0", features = ["macros"]} # <== changed here
```

When I run cargo test, I get:

```
error: failed to select a version for `cucumber_rust`.
    ... required by package `try_cucumber v0.1.0 (/path/to/try_cucumber)`
versions that meet the requirements `=0.7.3` are: 0.7.3

the package `try_cucumber` depends on `cucumber_rust`, with features: `macros` but `cucumber_rust` does not have these features.


failed to select a version for `cucumber_rust` which could resolve this conflict
```

That's all, folks! :slightly_smiling_face:

**Comment by bbqsrc** [comment]
The readme will be replaced by a book. In the mean time, there is [Florian's tutorial](https://www.florianreinhard.de/2020-10-05/cucumber-07-in-rust-beginners-tutorial/).

**Comment by alvskar** [comment]
I've added some of those suggestions and cleared up some confusion in the README; the macros require latest code from `main`.

That being said, the crate does not require nightly, so not sure what that's about.

**Comment by saveriomiroddi** [comment]
> I've added some of those suggestions and cleared up some confusion in the README; the macros require latest code from `main`.

Thanks for that! I'll redo the procedure to make sure it's beginner-proof :laughing: 

> That being said, the crate does not require nightly, so not sure what that's about.

It's possible that I was confused by the other problems, and that I've mentioned something wrong :grimacing:.

**Comment by saveriomiroddi** [comment]
I've tried the procedures again. The one highlighted in the [Auto-wiring via macros](https://github.com/bbqsrc/cucumber-rust#auto-wiring-via-macros) section now works fine.

I have still an issue with the non-macro version (the first example, essentially):

```rust
error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<impl futures::Future>` in the current scope
  --> playground/tests/cucumber.rs:41:17
   |
41 | /                 t!(|mut world, _step| {
42 | |                     world.foo = "elho".into();
43 | |                     world.test_async_fn().await;
44 | |                     world
45 | |                 }),
   | |__________________^ method not found in `AssertUnwindSafe<impl futures::Future>`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use futures::FutureExt;`
```

Now, this can be trivially fixed by:

```diff
diff --git i/playground/tests/cucumber.rs w/playground/tests/cucumber.rs
index b02a3b7..62bf531 100644
--- i/playground/tests/cucumber.rs
+++ w/playground/tests/cucumber.rs
@@ -30,6 +30,7 @@ async fn new() -> Result<Self, Infallible> {
 
 mod example_steps {
     use cucumber::{t, Steps};
+    use futures::FutureExt;
 
     pub fn steps() -> Steps<crate::MyWorld> {
         let mut builder: Steps<crate::MyWorld> = Steps::new();
```

There's something interesting going on here, because I had a discussion with Florian Reinhard about the same problem; on his machine this isn't required, but it is on mine, and the only difference I can think of is the O/S (Mac vs. Linux).

Are you running on a Mac? What happens if you add (or don't) the import above?

**Comment by saveriomiroddi** [comment]
By the way, thanks for the cleanup :pray:. I think it's very valuable for beginners to have a working, ready to use, template.

**Comment by alvskar** [comment]
Very odd. I am running on Linux (PopOS), and I cannot reproduce this issue.

Adding `use futures::FutureExt;` produces a warning:

```
warning: unused import: `futures::FutureExt`
  --> tests/cucumber.rs:33:9
   |
33 |     use futures::FutureExt;
```

My version of Rust: `rustc 1.47.0 (18bf6b4f0 2020-10-07)`

May be something messed up with the `futures` crate in the environment, I can't find anything on the error you're getting.

**Comment by saveriomiroddi** [comment]
> Very odd. I am running on Linux (PopOS), and I cannot reproduce this issue.
> 
> Adding `use futures::FutureExt;` produces a warning:
> 
> ```
> warning: unused import: `futures::FutureExt`
>   --> tests/cucumber.rs:33:9
>    |
> 33 |     use futures::FutureExt;
> ```
> 
> My version of Rust: `rustc 1.47.0 (18bf6b4f0 2020-10-07)`
> 
> May be something messed up with the `futures` crate in the environment, I can't find anything on the error you're getting.

Thanks for testing :slightly_smiling_face: 

Since it's already two machines where this can't be reproduced, I'll take it's just an issue with my system.

Closing the issue as resolved, and thanks everybody :pray:.
