### ISSUE TITLE
println! in steps

### ISSUE THREAD

**Issue by Chocrates** [bbqsrc/cucumber-rust#92]
Is it possible to print data to the console in steps for debugging?
It would be very useful while trying to get your regex right.

So something like this:

```rust
builder
    .given_regex_async(
        r#"^([a-z]$)",
        t!(|mut world, _match, _step| {
            println!("Hello World!");
            world
         }),
    );
```

**Comment by bbqsrc** [comment]
If you run `cargo test -- --nocapture`, all stdout will be printed (this is true for the ordinary tests and Cucumber tests). It might be nicer however to have a specific and clean way to capture and print it while debugging a step, but this is what we have for now. 😄

**Comment by Chocrates** [comment]
Hey thank you @bbqsrc that is good enough for my needs at the moment!
